"""Add mobile_token and sector_location_id to devices table

Revision ID: 009
Revises: 008
Create Date: 2026-03-18 17:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '009'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('mobile_token', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('sector_location_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'sector_location_id')
    op.drop_column('devices', 'mobile_token')
    # ### end Alembic commands ###
