"""add_assignment_note_to_report_assignments

Revision ID: 8249aed786d3
Revises: 009
Create Date: 2026-03-19 06:06:12.496898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8249aed786d3'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_groups',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('incident_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('center_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('center_long', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.incident_type_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    # Commented out: Cannot drop spatial_ref_sys as it's required by PostGIS extension
    # op.drop_table('spatial_ref_sys')
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_actor'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_entity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_time'), table_name='audit_logs')
    op.alter_column('case_reports', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('case_reports_added_by_fkey'), 'case_reports', type_='foreignkey')
    op.drop_column('case_reports', 'added_by')
    op.alter_column('cases', 'case_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('cases', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='report_priority'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::report_priority"))
    op.alter_column('cases', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
    op.alter_column('cases', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cases', 'closed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_cases_assigned'), table_name='cases', postgresql_where="((status)::text <> 'closed'::text)")
    op.drop_index(op.f('idx_cases_status'), table_name='cases')
    op.drop_constraint(op.f('cases_assigned_by_fkey'), 'cases', type_='foreignkey')
    op.drop_constraint(op.f('cases_assigned_to_fkey'), 'cases', type_='foreignkey')
    op.drop_column('cases', 'closure_notes')
    op.drop_column('cases', 'longitude')
    op.drop_column('cases', 'assigned_by')
    op.drop_column('cases', 'latitude')
    op.drop_column('cases', 'assigned_to')
    op.alter_column('devices', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('devices', 'blacklist_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_devices_hash'), table_name='devices')
    op.drop_index(op.f('idx_devices_trust'), table_name='devices')
    op.drop_column('devices', 'mobile_token')
    op.drop_column('devices', 'sector_location_id')
    op.drop_index(op.f('idx_evidence_hash'), table_name='evidence_files', postgresql_where='(perceptual_hash IS NOT NULL)')
    op.drop_index(op.f('idx_evidence_report'), table_name='evidence_files')
    op.drop_constraint(op.f('evidence_files_report_id_fkey'), 'evidence_files', type_='foreignkey')
    op.create_foreign_key(None, 'evidence_files', 'reports', ['report_id'], ['report_id'])
    op.alter_column('hotspots', 'radius_meters',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('hotspots', 'incident_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hotspots', 'risk_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='hotspot_risk'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'low'::hotspot_risk"))
    op.alter_column('hotspots', 'time_window_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hotspots', 'detected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_hotspots_location'), table_name='hotspots', postgresql_using='gist')
    op.drop_index(op.f('idx_hotspots_risk'), table_name='hotspots', postgresql_where='(is_active = true)')
    op.drop_column('hotspots', 'incident_type_distribution')
    op.drop_column('hotspots', 'hotspot_name')
    op.drop_column('hotspots', 'report_ids')
    op.drop_column('hotspots', 'is_active')
    op.drop_column('hotspots', 'expires_at')
    op.alter_column('incident_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('incident_types_type_name_key'), 'incident_types', type_='unique')
    op.drop_column('incident_types', 'color_code')
    op.alter_column('locations', 'location_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('idx_locations_geom'), table_name='locations', postgresql_using='gist')
    op.drop_index(op.f('idx_locations_parent'), table_name='locations')
    op.create_index('idx_locations_geometry', 'locations', ['geometry'], unique=False, postgresql_using='gist')
    op.drop_column('locations', 'created_at')
    op.alter_column('ml_predictions', 'evaluated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ml_final'), table_name='ml_predictions', postgresql_where='(is_final = true)')
    op.drop_index(op.f('idx_ml_report'), table_name='ml_predictions')
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('report', 'hotspot', 'assignment', 'system', 'alert', name='notification_type'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'system'::notification_type"))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'expires_at')
    op.alter_column('police_reviews', 'decision',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('police_reviews', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reviews_report'), table_name='police_reviews')
    op.drop_index(op.f('idx_reviews_training'), table_name='police_reviews', postgresql_where='(used_for_training = true)')
    op.drop_constraint(op.f('police_reviews_report_id_police_user_id_key'), 'police_reviews', type_='unique')
    op.alter_column('police_users', 'role',
               existing_type=postgresql.ENUM('admin', 'supervisor', 'officer', 'analyst', name='user_role'),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'officer'::user_role"))
    op.alter_column('police_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('police_users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_badge'), table_name='police_users')
    op.drop_index(op.f('idx_users_email'), table_name='police_users')
    op.drop_index(op.f('idx_users_role'), table_name='police_users', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_users_station'), table_name='police_users')
    op.drop_constraint(op.f('police_users_badge_number_key'), 'police_users', type_='unique')
    op.drop_column('police_users', 'last_password_change')
    op.drop_column('police_users', 'mfa_secret')
    op.drop_column('police_users', 'profile_picture_url')
    op.drop_column('police_users', 'mfa_enabled')
    op.drop_column('police_users', 'updated_at')
    op.add_column('report_assignments', sa.Column('assignment_note', sa.Text(), nullable=True))
    op.alter_column('report_assignments', 'status',
               existing_type=postgresql.ENUM('assigned', 'investigating', 'resolved', 'closed', name='assignment_status'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('report_assignments', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='report_priority'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('report_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_assignments', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_report_assignments_user'), table_name='report_assignments')
    op.drop_constraint(op.f('report_assignments_report_id_fkey'), 'report_assignments', type_='foreignkey')
    op.drop_constraint(op.f('report_assignments_police_user_id_fkey'), 'report_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'report_assignments', 'reports', ['report_id'], ['report_id'])
    op.create_foreign_key(None, 'report_assignments', 'police_users', ['police_user_id'], ['police_user_id'])
    op.alter_column('reports', 'report_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('reports', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reports', 'incident_type_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('reports', 'reported_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('pending', 'verified', 'flagged', 'rejected', name='report_status'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::report_status"))
    op.alter_column('reports', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('reports', 'verification_status',
               existing_type=postgresql.ENUM('pending', 'under_review', 'verified', 'rejected', name='verification_status'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::verification_status"))
    op.alter_column('reports', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reports', 'features_extracted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reports', 'context_tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment=None,
               existing_comment='Contextual tags from reporter (e.g. Night-time, Weapons involved, Multiple suspects).',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_reports_device'), table_name='reports')
    op.drop_index(op.f('idx_reports_incident_type'), table_name='reports')
    op.drop_index(op.f('idx_reports_location'), table_name='reports', postgresql_using='gist')
    op.drop_index(op.f('idx_reports_station'), table_name='reports')
    op.drop_index(op.f('idx_reports_status'), table_name='reports')
    op.drop_index(op.f('idx_reports_time'), table_name='reports')
    op.drop_index(op.f('idx_reports_verification'), table_name='reports', postgresql_where="(verification_status <> 'verified'::verification_status)")
    op.drop_constraint(op.f('reports_report_number_key'), 'reports', type_='unique')
    op.create_index(op.f('ix_reports_report_number'), 'reports', ['report_number'], unique=True)
    op.alter_column('stations', 'station_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('stations', 'station_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('stations', 'address_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('stations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_stations_active'), table_name='stations')
    op.drop_index(op.f('idx_stations_location'), table_name='stations')
    op.alter_column('system_config', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_sessions_token'), table_name='user_sessions', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('idx_sessions_user'), table_name='user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sessions_user'), 'user_sessions', ['police_user_id', 'expires_at'], unique=False)
    op.create_index(op.f('idx_sessions_token'), 'user_sessions', ['refresh_token'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.alter_column('user_sessions', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_config', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_stations_location'), 'stations', ['location_id'], unique=False)
    op.create_index(op.f('idx_stations_active'), 'stations', ['is_active'], unique=False)
    op.alter_column('stations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'address_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stations', 'station_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('stations', 'station_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_reports_report_number'), table_name='reports')
    op.create_unique_constraint(op.f('reports_report_number_key'), 'reports', ['report_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_reports_verification'), 'reports', ['verification_status'], unique=False, postgresql_where="(verification_status <> 'verified'::verification_status)")
    op.create_index(op.f('idx_reports_time'), 'reports', [sa.literal_column('reported_at DESC')], unique=False)
    op.create_index(op.f('idx_reports_status'), 'reports', ['status', 'is_flagged'], unique=False)
    op.create_index(op.f('idx_reports_station'), 'reports', ['handling_station_id'], unique=False)
    op.create_index(op.f('idx_reports_location'), 'reports', [sa.literal_column('st_makepoint(longitude::double precision, latitude::double precision)')], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_reports_incident_type'), 'reports', ['incident_type_id'], unique=False)
    op.create_index(op.f('idx_reports_device'), 'reports', ['device_id'], unique=False)
    op.alter_column('reports', 'context_tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment='Contextual tags from reporter (e.g. Night-time, Weapons involved, Multiple suspects).',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reports', 'features_extracted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reports', 'verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reports', 'verification_status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'under_review', 'verified', 'rejected', name='verification_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::verification_status"))
    op.alter_column('reports', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('reports', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'verified', 'flagged', 'rejected', name='report_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::report_status"))
    op.alter_column('reports', 'reported_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'incident_type_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('reports', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reports', 'report_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'report_assignments', type_='foreignkey')
    op.drop_constraint(None, 'report_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('report_assignments_police_user_id_fkey'), 'report_assignments', 'police_users', ['police_user_id'], ['police_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('report_assignments_report_id_fkey'), 'report_assignments', 'reports', ['report_id'], ['report_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_report_assignments_user'), 'report_assignments', ['police_user_id'], unique=False)
    op.alter_column('report_assignments', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('report_assignments', 'assigned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_assignments', 'priority',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='report_priority'),
               existing_nullable=False)
    op.alter_column('report_assignments', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('assigned', 'investigating', 'resolved', 'closed', name='assignment_status'),
               existing_nullable=False)
    op.drop_column('report_assignments', 'assignment_note')
    op.add_column('police_users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('police_users', sa.Column('mfa_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('police_users', sa.Column('profile_picture_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('police_users', sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('police_users', sa.Column('last_password_change', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('police_users_badge_number_key'), 'police_users', ['badge_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_station'), 'police_users', ['station_id'], unique=False)
    op.create_index(op.f('idx_users_role'), 'police_users', ['role'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_users_email'), 'police_users', ['email'], unique=False)
    op.create_index(op.f('idx_users_badge'), 'police_users', ['badge_number'], unique=False)
    op.alter_column('police_users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('police_users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('police_users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('admin', 'supervisor', 'officer', 'analyst', name='user_role'),
               nullable=True,
               existing_server_default=sa.text("'officer'::user_role"))
    op.create_unique_constraint(op.f('police_reviews_report_id_police_user_id_key'), 'police_reviews', ['report_id', 'police_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_reviews_training'), 'police_reviews', ['used_for_training'], unique=False, postgresql_where='(used_for_training = true)')
    op.create_index(op.f('idx_reviews_report'), 'police_reviews', ['report_id'], unique=False)
    op.alter_column('police_reviews', 'reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('police_reviews', 'decision',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('notifications', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='report_priority'), server_default=sa.text("'medium'::report_priority"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['police_user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('report', 'hotspot', 'assignment', 'system', 'alert', name='notification_type'),
               nullable=True,
               existing_server_default=sa.text("'system'::notification_type"))
    op.create_index(op.f('idx_ml_report'), 'ml_predictions', ['report_id'], unique=False)
    op.create_index(op.f('idx_ml_final'), 'ml_predictions', ['report_id'], unique=False, postgresql_where='(is_final = true)')
    op.alter_column('ml_predictions', 'evaluated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('locations', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index('idx_locations_geometry', table_name='locations', postgresql_using='gist')
    op.create_index(op.f('idx_locations_parent'), 'locations', ['parent_location_id'], unique=False)
    op.create_index(op.f('idx_locations_geom'), 'locations', ['geometry'], unique=False, postgresql_using='gist')
    op.alter_column('locations', 'location_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('incident_types', sa.Column('color_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('incident_types_type_name_key'), 'incident_types', ['type_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('incident_types', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('hotspots', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hotspots', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('hotspots', sa.Column('report_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.add_column('hotspots', sa.Column('hotspot_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hotspots', sa.Column('incident_type_distribution', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_hotspots_risk'), 'hotspots', ['risk_level'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_hotspots_location'), 'hotspots', [sa.literal_column('st_makepoint(center_long::double precision, center_lat::double precision)')], unique=False, postgresql_using='gist')
    op.alter_column('hotspots', 'detected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hotspots', 'time_window_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotspots', 'risk_level',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('low', 'medium', 'high', 'critical', name='hotspot_risk'),
               nullable=True,
               existing_server_default=sa.text("'low'::hotspot_risk"))
    op.alter_column('hotspots', 'incident_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hotspots', 'radius_meters',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.drop_constraint(None, 'evidence_files', type_='foreignkey')
    op.create_foreign_key(op.f('evidence_files_report_id_fkey'), 'evidence_files', 'reports', ['report_id'], ['report_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_evidence_report'), 'evidence_files', ['report_id'], unique=False)
    op.create_index(op.f('idx_evidence_hash'), 'evidence_files', ['perceptual_hash'], unique=False, postgresql_where='(perceptual_hash IS NOT NULL)')
    op.add_column('devices', sa.Column('sector_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('mobile_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_devices_trust'), 'devices', ['device_trust_score'], unique=False)
    op.create_index(op.f('idx_devices_hash'), 'devices', ['device_hash'], unique=False)
    op.alter_column('devices', 'blacklist_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('devices', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('devices', 'first_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('cases', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('closure_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cases_assigned_to_fkey'), 'cases', 'police_users', ['assigned_to'], ['police_user_id'])
    op.create_foreign_key(op.f('cases_assigned_by_fkey'), 'cases', 'police_users', ['assigned_by'], ['police_user_id'])
    op.create_index(op.f('idx_cases_status'), 'cases', ['status', 'priority'], unique=False)
    op.create_index(op.f('idx_cases_assigned'), 'cases', ['assigned_to'], unique=False, postgresql_where="((status)::text <> 'closed'::text)")
    op.alter_column('cases', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cases', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cases', 'closed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cases', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cases', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cases', 'priority',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='report_priority'),
               nullable=True,
               existing_server_default=sa.text("'medium'::report_priority"))
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('cases', 'case_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('case_reports', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('case_reports_added_by_fkey'), 'case_reports', 'police_users', ['added_by'], ['police_user_id'])
    op.alter_column('case_reports', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_audit_time'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_audit_actor'), 'audit_logs', ['actor_type', 'actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('incident_groups')
    # ### end Alembic commands ###
